blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
 #   url(r'^$', views.index, name='index'),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^blog/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^gallery/$', views.gallery, name='gallery'),
    url(r'^contact/$', views.contact, name='contact'),
    ]

sbsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from blog import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^login/$', views.user_login, name="user_login"),
    url(r'^logout/$', views.user_logout, name="user_logout"),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
# from ckeditor.fields import RichTextField
class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    photo = models.ImageField(blank=True, null=True)
    #content = models.TextField()
    content = RichTextUploadingField(blank=True, null=True)
    content2 = RichTextUploadingField(blank=True, null=True, config_name='special', external_plugin_resources=[(
                                          'youtube',
                                          '/static/vendor/ckeditor_plugins/youtube/youtube/',
                                          'plugin.js',
                                          )],
        )
     # photo = models.ImageField( null=True)
    is_public = models.BooleanField(default=False)
#    새로운 필드 추가 첫째 makemigrations App 둘째 migrate App
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.id]) 

class Images(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE,)
	image = models.ImageField(upload_to='images/', blank=True, null=True)
		

	def __str__(self):
		return self.post.title + "Image"
        # return self.post.title + "Image"

blog/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post

# from django import forms
# from .models import Post, Images

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title','content','content2']
# class PostForm(forms.ModelForm):
#     title = forms.CharField(max_length=128)
#     content = forms.CharField(max_length=245, label="content")
    
#     class Meta:
#         model = Post
#         fields = (
#             'title',
#             'content',
#              )

        
# class ImageForm(forms.ModelForm):
#     image = forms.ImageField(label='image')
#     class Meta:
#         model = Images
#         fields = ('image',)
        

class UserLoginForm(forms.Form):
    username = forms.CharField(label="")
    password = forms.CharField(label="", widget=forms.PasswordInput)
    

blog/views.py
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.urls import reverse
from .models import Post, Images
# from .forms import PostForm, UserLoginForm, ImageForm forms에서 imageform지움>>
from .forms import PostForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect

# from django.forms import modelformset_factory
# Create your views here.
def post_list(request):
    post_list= Post.objects.all()
    return render(request,'blog/post_list.html',{'post_list':post_list,})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request,'blog/post_detail.html',{'post':post}) 

def post_new(request):

    # ImageFormset = modelformset_factory(Images, field=('image',), extra=4)
    # ImageFormSet = modelformset_factory(Images, form=ImageForm, extra=3,)
    if request.method == "POST":

        form = PostForm(request.POST)
        # formset = ImageFormSet(request.POST or None, request.FILES or None)

        # if form.is_valid() and formset.is_valid():
        if form.is_valid() :
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()

            # for form in formset.cleaned_data:
            #      try:
            #          image = form['image']
            #          photo = Images(post=post_form, image=image)
            #          photo.save()
            #          return redirect('post_list')
                
            #      except Exception as e:
            #          pass
            return redirect('post_detail', pk=post.pk)
            
            # for f in formset:
            #     try:
                    
            #         photo = Images(post=post, image=f.cleaned_data['image'])
            #         photo.save()
                   
                
            #     except Exception as e:
            #         break
            # return redirect('post_detail', pk=post.pk)

    else:
        form = PostForm()
        # formset = ImageFormSet(queryset=Images.objects.none())
    return render(request, 'blog/post_edit.html', {'form': form,})
    # return render(request, 'blog/post_edit.html', {'form': form, 'formset':formset,})


def user_login(request):
    if request.method == "POST":
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                if user.is_active:
            
                    login(request, user)
                    return HttpResponseRedirect(reverse('post_list'))
                else:
                    return HttpResponse("등록된 사용자가 아닙니다.")    
            else:
                return HttpResponse("등록된 사용자가 아닙니다.")  
    else:
        form = UserLoginForm()

    context = {
        'form' : form,
    }    

    return render(request, 'blog/login.html', context)

def user_logout(request):  
    logout(request)
    return redirect('post_list') 



def gallery(request):
    
    return render(request,'blog/gallery.html')     
 
def contact(request):
    
    return render(request,'blog/contact.html')         

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>창작미술</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
   <!--  <link href="{% static 'css/main.css' %}" rel="stylesheet"> -->
    <link href="{% static 'css/resume.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">창작미술</span>
        <span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'img/rainbowic.png' %}" alt="">
          <p class="small">since 2002</p>
        </span>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'post_list' %}">홈</a>
          </li>
             
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'gallery' %}">갤러리</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'contact' %}">상담문의</a>
          </li>
          
          {% if user.is_authenticated %}
          
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span>Hi {{ request.user }} </span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'post_new' %}"> &nbsp;Edit</a>
           
          <a class="dropdown-item" href="{% url 'user_logout' %}"> &nbsp;Logout</a>
        </div>
      </li>
      {% else %}
        <li class="nav-item">
        <a class="nav-link" href="{% url 'user_login' %}">관리자</a>
      </li>
      {% endif %}
         
        </ul>
      </div>
    </nav>
    {% block content %}
    {% endblock %}

    <footer class="footer text-center py-2" style="background-color:#cce0ff">
                      
                 <p>Copyright &copy; <a  class="js-scroll-trigger" href="#page-top" style="color: #8BC9C">창작미술 </a>2019</p>
    </footer>  

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/resume.min.js' %}"></script>
    <script src="{% static 'js/resume.min.js' %}"></script>

  </body>

</html>

blog/templates/blog/contact.html
{% extends 'blog/base.html' %}
{% load static from staticfiles %}

@import url('https://fonts.googleapis.com/css?family=Lobster');
{% block content %}


 <div class="container-fluid p-0">
    <hr class="m-0">

      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="">
        <div class="my-auto">
        <h2 class="mb-5"></h2>

        <div class="resume-item d-flex flex-column flex-md-row">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">상담 문의</h3>
              <div class="subheading mb-3"> </div>
               <h5 class="card-title pt-3">메일보내기</h5>
              <form class="form-horizontal" role="form" method="post"  action="https://formspree.io/25tens@naver.com">
  <div class="form-group">
    <label for="name" class="col-sm-2 control-label">이름</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="name" name="name" placeholder="" value="">
    </div>
  </div>
  <div class="form-group">
    <label for="email" class="col-sm-2 control-label">이메일</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="email" name="email" placeholder="example@domain.com" value="">
    </div>
  </div>
  <div class="form-group">
    <label for="message" class="col-sm-2 control-label">메세지</label>
    <div class="col-sm-10">
      <textarea class="form-control" rows="4" name="message"></textarea>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-2">
      <! Will be used to display an alert to the user>
    </div>
  </div>
</form>
                <div class="card-deck m-b-1">

                	 <div class="card border-0">
                    <div class="card-block">
                    	  <h5 class="card-title pt-3">위치보기</h5>
                          
                         <div class="map-responsive">
							<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6521.79617728619!2d128.79113156817334!3d35.18409251527917!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3568cf13ea64cfb9%3A0x59eb9d9a392499f5!2z64yA7ZWc66-86rWtIOqyveyDgeuCqOuPhCDquYDtlbTsi5wg7J6l7Jyg66m0IOqzhOuPmeuhnCA4Ng!5e0!3m2!1sko!2skr!4v1467588518834" width="293" height="300" frameborder="0" style="border:0" allowfullscreen></iframe> 
						
                        </div>
                    </div>
                 </div>
               <div class="card border-0">
                    <div class="card-block">

                       
                        <h5 class="card-title pt-3"></h5>
                         <table class="table table-borderless">
    <thead>
      <tr>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td></td>
        <td><i class="fas fa-h-square"></i></td>
        <td>김해시 계동로86</td>
      </tr>
      <tr>
        <td></td>
        <td><i class="fas fa-phone-square"></i></td>
        <td>055-311-3738</td>
      </tr>
       <tr>
        <td></td>
        <td><i class="fas fa-envelope-square"></i></td>
        <td>info@chang-jak.com</td>
      </tr>
    </tbody>
  </table>
          </div>
                   </div>

               
            </div>
            </div>
           </div>
      </div>
      </section>
     </div>
      <hr class="m-0">

<script>
function myMap() {
var mapProp= {
  center:new google.maps.LatLng(51.508742,-0.120850),
  zoom:5,
};
var map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY&callback=myMap"></script>
                     
{% endblock  %} 

blog/templates/blog/gallery.html
{% extends 'blog/base.html' %}
{% load static from staticfiles %}

<!-- @import url('https://fonts.googleapis.com/css?family=Lobster'); -->

{% block extra_head %}
      
       <style>
           .post_photo { max-width: 400px;
                         max-height: 350px;
                        }
          
                 
       </style>
 {% endblock %}

{% block content %}

 <div class="container-fluid p-0">

   
     
      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="">
        <div class="my-auto">
         <!--  <h2 class="mb-5">3D PRINTABLE FILES & 3D MODELS</h2> -->
           <h2 class="mb-5">gallery</h2>
               <p class="text-primary"></p>
               

                <hr class="m-0">
        </div>
    
         <div class="my-auto">
          <div class="resume-item d-flex flex-column flex-md-row mb-4">
          <div class="resume-content mr-auto col-6">
          <img src="http://res.cloudinary.com/yesnet/image/upload/v1475557197/ch1005_xb8u3v.png" class="img-responsive pt-3"
          style="width: 350px;height: 350px" alt="">
          <div>도시야경</div>
              <p>10세</p>
          </div>

          <div class="resume-content mr-auto col-6">
             
            
               <img src="http://res.cloudinary.com/yesnet/image/upload/v1475557199/ch1006_y6tvyz.png" alt="" class=img-responsive pt-3" 
               style="width: 350px;height: 350px"/>
                
              <div>거북이</div>
              <p>8세</p>
            </div>
            
          </div>
           <div class="resume-item d-flex flex-column flex-md-row mb-4">
            <div class="resume-content mr-auto col-6">
              
             <img src="http://res.cloudinary.com/yesnet/image/upload/v1475557198/ch1003_qsqgdn.png" class=img-responsive pt-3" 
               style="width: 350px;height: 350px"  alt="" />
               
              <div>포도밭</div>
              <p>9세</p>
            </div>
             <div class="resume-content mr-auto col-6">
            
             
               <img src="http://res.cloudinary.com/yesnet/image/upload/v1475557198/ch1002_gkhsdu.png" class=img-responsive pt-3" 
               style="width: 350px;height: 350px" alt="" />
                 
              <div>강강술래 </div>
              <p>9세
</p>
            </div>
           </div>
           <div class="resume-item d-flex flex-column flex-md-row mb-4">
            <div class="resume-content mr-auto col-6">
            
               <img src="http://res.cloudinary.com/yesnet/image/upload/v1475557197/ch1001_bt2vxr.png" class=img-responsive pt-3" 
               style="width: 350px;height: 350px" alt="" />
                 
              <div>산책로</div>
              <p>11세
</p>
            </div>
             <div class="resume-content mr-auto col-6">
              
               <img src="http://res.cloudinary.com/yesnet/image/upload/v1472610092/ch316_kjcm1x.png" class=img-responsive pt-3" 
               style="width: 350px;height: 350px" alt="" />
               
              <div>옥수수</div>
              <p>13세
</p>
            </div>
            
            <!-- <div class="resume-date text-md-right">
              <span class="text-primary">August 2006 - May 2010</span>
            </div> -->
          </div>
 
         <div class="resume-item d-flex flex-column flex-md-row mb-4">
            <div class="resume-content mr-auto col-6">
             
               <img src="http://res.cloudinary.com/yesnet/image/upload/v1472610093/ch315_hqweiu.png"  class=img-responsive pt-3" 
               style="width: 350px;height: 350px" alt="" />
                 
              <div>집앞</div>
              <p>11세
</p>
            </div>
             <div class="resume-content mr-auto col-6">
             
               <img src="http://res.cloudinary.com/yesnet/image/upload/v1472610091/ch314_ht6yaq.png" class=img-responsive pt-3" 
               style="width: 350px;height: 350px" alt="" />
                
              <div>벽돌</div>
              <p>11세
</p>
            </div>
            
            <!-- <div class="resume-date text-md-right">
              <span class="text-primary">August 2006 - May 2010</span>
            </div> -->
          </div>
 
          <div class="resume-item d-flex flex-column flex-md-row mb-4">
            <div class="resume-content mr-auto col-6">
             
               <img src="http://res.cloudinary.com/yesnet/image/upload/v1472610091/ch311_d60lpz.png"  class=img-responsive pt-3" 
               style="width: 350px;height: 350px" alt="" />
                 
              <div>수박 먹어요</div>
              <p>8세
</p>
            </div>
             <div class="resume-content mr-auto col-6">
             
               <img src="http://res.cloudinary.com/yesnet/image/upload/v1472610091/ch312_wg5g7j.png" class=img-responsive pt-3" 
               style="width: 350px;height: 350px" alt="" />
                
              <div>공작새</div>
              <p>7세
</p>
            </div>
            
            <!-- <div class="resume-date text-md-right">
              <span class="text-primary">August 2006 - May 2010</span>
            </div> -->
          </div>
        

        </div>
      </section>
    </div>

  
 
             
  
 



 {% endblock  %} 

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% load static from staticfiles %}


{% block content %}

<div class="container-fluid p-0">
    <hr class="m-0">

      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="education">
        <div class="my-auto">
          <h2 class="mb-5">login</h2>

          <div class="resume-item d-flex flex-column flex-md-row mb-5">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">so-boon</h3>
              <div class="subheading mb-3">
               </div>
                <form method="post">
             {% csrf_token %}
             {{ form.as_p}}
          <input type="submit" value="Login" class="btn btn-outline-success">
        </form> 
            </div>
          
          </div>

 

        </div>
      </section>
	 
      
</div>
 

{% endblock %}

 

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static from staticfiles %}

<!-- @import url('https://fonts.googleapis.com/css?family=Lobster'); -->
{% block content %}

<div class="container-fluid p-0">
  <section class="resume-section p-3 p-lg-5 d-flex flex-column creative-content" id="">
    <div class="my-auto">
          <h2 class="mb-5"></h2>
          <p class="text-primary"> --- </p>
   

    <div class="container">
          <header class="blog-post-header">
             {% if post.photo %}
                <img class="img-fluid" src="{{ post.photo.url }}" alt="image">
                {% endif %}  
           
          </header>
  
          <div class="blog-post-body">
           <figure class="blog-banner">
              <h5 class="title mb-2"></h5>

            <div class="meta mb-3"></div>  
                
             <p> {{ post.content | safe }}
                {{ post.content2 | safe }} 
             <!--  {{ post.content|linebreaksbr }} -->
               
             </p>
            <!--  <p>{{ post.published_date }}</p> -->
             <input type="button" value="return" class="btn btn-primary btn-lg rounded-0 mt-3" onClick="javascript:history.go(-1);">
          </div>  
        </div>

    </div>
  </section>
 </div>


{% endblock %}


   <!--  <section class="creative-content"> -->
    <div class="container">
        <div class="row d-flex align-items-center h-100">
            <div class="col-12 col-lg-6">
                <div class="img-box text-left">
                  {% for p in post.images_set.all %}
         
            <img src="{{ p.image.url }}" class="">
         
                   {% endfor %} 
                   
                </div>
            </div>
            <div class="col-12 col-lg-6">
                <div class="content-box">
                    <h2><span class="font-weight-bold d-block"></span>
                     <span class="font-weight-light">
                      {{ post.title }}
                      {{ post.content|safe }}
                      {{ post.content2|safe }} </span>
                   </h2>
                   
                   <!--  <p class="mt-4"> 
                                      {{ post.content|linebreaksbr }}
                                      {% if post.published_date %}
                                       {% endif %} </p> -->
                   
                   <input type=button value="이전페이지" class="btn btn-primary btn-lg rounded-0 mt-3" onClick="javascript:history.go(-1);">
                </div>
            </div>
        </div>
    </div>

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load static from staticfiles %}

<!-- @import url('https://fonts.googleapis.com/css?family=Lobster'); -->
{% block content %}


<div class="container-fluid p-0">
    <hr class="m-0">

      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="education">
        <div class="my-auto">
          <h2 class="mb-5">edit</h2>

          <div class="resume-item d-flex flex-column flex-md-row mb-5 col-8">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">   </h3>
             
             
          
              <div class="subheading mb-3">
               </div>

               <!-- <form id="post_form" method="post" action="" style="margin: 0 20% 0 20%;padding: 10px;" enctype="multipart/form-data">
   
                       {% csrf_token %}
                       {{ form.as_p }}
                     <ul  class="imgli"><li>{{ formset.as_table }}</li></ul>
   
                      <br><br>
                     <input type="submit" name="submit" value="Submit" />
              </form> -->
              <form method="POST" action="">
             {% csrf_token %}
             {{ form.media }}
             {{ form }}
             <input type="submit" value="Save">
             </form>
               
            </div>
          
          </div>

 

        </div>
      </section>
  </div>
	
{% endblock %}